let
    Source = Csv.Document(File.Contents("\\Mac\Home\Portfolio Projects\Polar\06.03.2020\year_activity.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{""}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Date", type date}, {"Steps", Int64.Type}, {"Km based on steps", type number}, {"Calories burned", Int64.Type}, {"Inactivity stamps", Int64.Type}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"Date", "Steps", "Km based on steps", "Calories burned", "Inactivity stamps", "Active time", "Sleep time"}),
    #"Split Column by Character Transition" = Table.SplitColumn(#"Reordered Columns", "Active time", Splitter.SplitTextByCharacterTransition((c) => not List.Contains({"0".."9"}, c), {"0".."9"}), {"Active time.1", "Active time.2"}),
    #"Split Column by Character Transition1" = Table.SplitColumn(#"Split Column by Character Transition", "Active time.2", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"Active time.2.1", "Active time.2.2"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Split Column by Character Transition1",{"Active time.2.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"Active time.2.1", Int64.Type}}),
    #"Divided Column" = Table.TransformColumns(#"Changed Type1", {{"Active time.2.1", each _ / 60, type number}}),
    #"Split Column by Character Transition2" = Table.SplitColumn(#"Divided Column", "Active time.1", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"Active time.1.1", "Active time.1.2"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Split Column by Character Transition2",{"Active time.1.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns2",{{"Active time.2.1", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type2","0","",Replacer.ReplaceText,{"Active time.2.1"}),
    #"Merged Columns" = Table.CombineColumns(#"Replaced Value",{"Active time.1.1", "Active time.2.1"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Active time"),
    #"Changed Type3" = Table.TransformColumnTypes(#"Merged Columns",{{"Active time", type number}}),
    #"Split Column by Character Transition3" = Table.SplitColumn(#"Changed Type3", "Sleep time", Splitter.SplitTextByCharacterTransition((c) => not List.Contains({"0".."9"}, c), {"0".."9"}), {"Sleep time.1", "Sleep time.2"}),
    #"Split Column by Character Transition4" = Table.SplitColumn(#"Split Column by Character Transition3", "Sleep time.1", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"Sleep time.1.1", "Sleep time.1.2"}),
    #"Split Column by Character Transition5" = Table.SplitColumn(#"Split Column by Character Transition4", "Sleep time.2", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"Sleep time.2.1", "Sleep time.2.2"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Split Column by Character Transition5",{"Sleep time.1.2", "Sleep time.2.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Removed Columns3",{{"Sleep time.2.1", Int64.Type}}),
    #"Divided Column1" = Table.TransformColumns(#"Changed Type4", {{"Sleep time.2.1", each _ / 60, type number}}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Divided Column1",{{"Sleep time.2.1", type text}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type5","0","",Replacer.ReplaceText,{"Sleep time.2.1"}),
    #"Merged Columns1" = Table.CombineColumns(#"Replaced Value1",{"Sleep time.1.1", "Sleep time.2.1"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Merged"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Columns1",{{"Merged", "Sleep time"}}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Renamed Columns",{{"Sleep time", type number}}),
    #"Rounded Off" = Table.TransformColumns(#"Changed Type6",{{"Sleep time", each Number.Round(_, 2), type number}}),
    #"Rounded Off1" = Table.TransformColumns(#"Rounded Off",{{"Active time", each Number.Round(_, 2), type number}})
in
    #"Rounded Off1"
